apiVersion: v2
name: edge
home: https://www.mezmo.com
icon: https://app.mezmo.com/assets/img/mz-logo-square-128.png
description: A Helm chart for deploying Mezmo Edge
type: application
appVersion: "6.5.1"
version: 1.4.3
maintainers:
  - name: Mezmo
    email: help@mezmo.com
