{{- if .Values.useDaemonSet -}}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "edge.fullname" . }}
  labels:
    {{- include "edge.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "edge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "edge.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "edge.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: data
          hostPath:
            path: {{ .Values.daemonsetVolumeHostPath | quote }}
            type: DirectoryOrCreate
        - name: config
          projected:
            sources:
              - configMap:
                  name: {{ include "edge.fullname" . }}
        {{- if .Values.enableK8sLogs }}
        - hostPath:
            path: /var/log/
          name: var-log
        - hostPath:
            path: /var/lib/
          name: var-lib
        {{- with .Values.k8sAdditionalHostPaths }}
        {{- range . }}
        - name: {{ .name }}
          hostPath:
            path: {{ .path }}
        {{- end }}
        {{- end }}
        {{- end }}
      terminationGracePeriodSeconds: 60
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: MEZMO_API_HOST
            value: {{ .Values.mezmoApiHost | quote }}
          - name: MEZMO_API_SCHEME
            value: {{ .Values.mezmoApiScheme | quote }}
          - name: MEZMO_LOCAL_DEPLOY_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                {{ include "edge.tokenSecretRef" . | nindent 16  }}
                key: api-access-token
          - name: MEZMO_METRICS_ENDPOINT_URL
            value: "{{include "edge.mezmoApiBaseUrl" . }}/v3/pipeline/account/local-deploy/metric/usage?edge_id={{include "edge.Id" . | urlquery }}"
          - name: MEZMO_TASKS_FETCH_ENDPOINT_URL
            value: "{{include "edge.mezmoApiBaseUrl" . }}/v3/pipeline/account/local-deploy/tasks?edge_id={{include "edge.Id" . | urlquery }}"
          - name: MEZMO_TASKS_POST_ENDPOINT_URL
            value: "{{include "edge.mezmoApiBaseUrl" . }}/v3/pipeline/account/local-deploy/tasks/:task_id/results"
          - name: MEZMO_EDGE_ID
            value: {{include "edge.Id" . | quote }}
          - name: MEZMO_TASK_INITIAL_POLL_DELAY
            value: {{ .Values.remoteTaskInitialPollDelay | quote }}
          - name: MEZMO_REMOTE_TASK_POLL_STEP_DELAY
            value: {{ .Values.remoteTaskPollStepDelay | quote }}
          - name: MEZMO_REMOTE_TASK_EXECUTION_TIMEOUT
            value: {{ .Values.remoteTaskExecutionTimeout | quote }}
          - name: VECTOR_LOG
            value: {{ .Values.logLevel | quote }}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_INDEX_LABEL
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          {{- if .Values.enableK8sLogs }}
          - name: EDGE_SELF_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          {{- end }}
          - name: MEZMO_RESHAPE_MESSAGE
            value: "1"
          {{- if .Values.maxDiskBufferBytes }}
          - name: MEZMO_DISK_BUFFER_MAX_BYTES
            value: {{ .Values.maxDiskBufferBytes | quote }}
          {{- end }}
          {{- if .Values.maxMemBufferEvents }}
          - name: MEZMO_MEM_BUFFER_MAX_EVENTS
            value: {{ .Values.maxMemBufferEvents | quote }}
          {{- end }}
          - name: REDUCE_BYTE_THRESHOLD_PER_STATE
            value: {{ .Values.reduceByteThresholdPerState | quote }}
          - name: REDUCE_BYTE_THRESHOLD_ALL_STATES
            value: {{ .Values.reduceByteThresholdAllStates | quote }}
          args:
            - --config-dir
            - /etc/vector/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: "/data/vector"
            - name: config
              mountPath: "/etc/vector/"
              readOnly: true
            {{- if .Values.enableK8sLogs }}
            - mountPath: /var/log/
              name: var-log
              readOnly: true
            - mountPath: /var/lib/
              name: var-lib
              readOnly: true
            {{- with .Values.k8sAdditionalHostPaths }}
            {{- range . }}
            - name: {{ .name }}
              mountPath: {{ .path }}
              readOnly: true
            {{- end }}
            {{- end }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end}}
